export const data = [
{   _id: 1,
    name: "Trendies Black Dial",
    price: 10,
    countInStock: 20,
    decription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo vel modi eum ipsum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/38058PP01_1.jpg?pView=listing"
},
{   _id: 2,
    name: "Trendis Dark Grey",
    price: 30,
    countInStock: 20,
    decription: "Adipisicing elit. Explicabo vel modi eum ipsum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "Watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/38058PP02_1.jpg?pView=listing"
},
{   _id: 3,
    name: "Silicon Strap",
    price: 50,
    countInStock: 20,
    decription: "Lorem ipsum dolor, sit amet consectetur psum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "Watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/38057PP01_1.jpg?pView=listing"
},
{   _id: 4,
    name: "Silicon Strap Black",
    price: 34,
    countInStock: 30,
    decription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo vel modi eum ipsum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "Watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/38057PP03_1.jpg?pView=listing"
},
{   _id: 5,
    name: "All Nighters Blue",
    price: 68,
    countInStock: 30,
    decription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo vel modi eum ipsum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "Watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/3195AP02_1.jpg?pView=listing"
},
{   _id: 6,
    name: "Fast Fit Watch",
    price: 53,
    countInStock: 30,
    decription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo vel modi eum ipsum quia nostrum quaerat quas quisquam assumenda. Inc_idunt",
    catagory: "Watch",
    photo: "https://staticimg.titan.co.in/Fastrack/Catalog/3224NL02_1.jpg?pView=listing"
},
]