export const LIST_PRODUCT_REQUEST = "LIST_PRODUCT_REQUEST";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_PRODUCT_FAIL = "LIST_PRODUCT_FAIL";


export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST";
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS";
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL";